### ISSUE TITLE
Not an issue : Future support of python-pdfbox.

### ISSUE THREAD

**Issue by maddy2021** [lebedov/python-pdfbox#17]
pdfbox has largely used the package in java and i liked it. Now I have to read pdf file in python and you have done the superb job so are you going to provide support-related pdfbox all function related to extracting data from pdf?
Can I extract headings from pdf using this library?

**Comment by lebedov** [comment]
I wasn't planning to add support for pdfbox's full API at the present time, mainly because of limited time on my part and the fact that I'm not using python-pdfbox much at the present (python-pdfbox wraps pdfbox's command-line interface rather than the full API). I suspect you probably would need to make use of pdfbox's [PDFTextStripperByArea](https://pdfbox.apache.org/docs/2.0.1/javadocs/org/apache/pdfbox/text/PDFTextStripperByArea.html) class; take a look at [this gist](https://gist.github.com/lebedov/cefbec588c2b2bd0251ba505bd8bf933) for an example of how to access pdfbox's full API from Python.
