### ISSUE TITLE
Unable to pass path to the PDF file on google cloud

### ISSUE THREAD

**Issue by mudasserch1** [lebedov/python-pdfbox#31]
Hey.
I am working to read data from the cloud and it's around 800k resume I want to read. Is there any way to use the google cloud path in extract_text function?

My error is:
java.io.FileNotFoundException: java.io.FileNotFoundException 

This means path not found but when I copy the same link in the browser it shows me a valid resume.

**Comment by lebedov** [comment]
Not directly - the issue is that the Java pdfbox package wrapped by python-pdfbox doesn't know how to deal with files that need to be downloaded over a network.

One possibility you might want to explore is to download the data (e.g., with python [requests](https://requests.readthedocs.io/en/latest/) or some other library) to a temporary file and pass that to python-pdfbox.

**Comment by mudasserch1** [comment]
Thanks @lebedov
